FROM node:16-alpine as builder

WORKDIR /usr/app

COPY package*.json ./
RUN npm ci

COPY . .

FROM builder as compiler

RUN npm run build

FROM node:16-alpine as production

WORKDIR /usr/app
COPY --from=compiler /usr/app/package*.json ./
COPY --from=compiler /usr/app/build ./

RUN npm ci --only=production

FROM gcr.io/distroless/nodejs:16
WORKDIR /usr/app
COPY --from=production /usr/app ./

EXPOSE 8080

CMD ["./server.js"]
