FROM node:16-alpine as builder

WORKDIR /usr/app

COPY package*.json ./
RUN npm ci

COPY . .

FROM builder as compiler

RUN npm run build

FROM node:16-alpine as production

WORKDIR /usr/app
COPY --from=builder /usr/app/package*.json ./
COPY --from=builder /usr/app/build ./

RUN npm ci --only=production

EXPOSE 8080

CMD ["node", "./server.js"]
