FROM node:22-alpine AS builder

WORKDIR /usr/app

COPY package*.json ./
RUN npm ci

COPY . .

FROM builder AS compiler

RUN npm run build

FROM node:22-alpine AS production

WORKDIR /usr/app
COPY --from=compiler /usr/app/package*.json ./
COPY --from=compiler /usr/app/build ./

RUN npm ci --only=production

FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /usr/app
COPY --from=production /usr/app ./

EXPOSE 8080

CMD ["./server.js"]
